version: 1.0.0.{build}
os: Visual Studio 2015
install:
- cmd: nuget install redis-64 -OutputDirectory packages -excludeversion 
- cmd: packages\redis-64\tools\redis-server.exe --service-install
- cmd: packages\redis-64\tools\redis-server.exe --service-start
environment:
  COVERALLSKEY:
    secure: foPTkHxSG+6pFNIuyuenQyooOGlv4Ragvti66cvQcnejTcFWdJr3/tNo/3seGBum
test: off
build_script:
- cmd: build.cmd ci coverallskey=%COVERALLSKEY%
cache:
- packages -> **\packages.config
