version: 1.0.0.{build}
os: Visual Studio 2015
environment:
  COVERALLSKEY:
    secure: foPTkHxSG+6pFNIuyuenQyooOGlv4Ragvti66cvQcnejTcFWdJr3/tNo/3seGBum
test: off
build_script:
- cmd: build.cmd ci coverallskey=%COVERALLSKEY%
cache:
- packages -> **\packages.config
